{{- if .Values.loki.enabled }}
---
kind: BucketClaim
apiVersion: objectstorage.k8s.io/v1alpha1
metadata:
  name: loki-bucket
spec:
  bucketClassName: ceph-rgw
  protocols:
    - s3
---
kind: BucketAccess
apiVersion: objectstorage.k8s.io/v1alpha1
metadata:
  name: loki-bucket
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  bucketAccessClassName: ceph-rgw
  bucketClaimName: loki-bucket
  protocol: s3
  credentialsSecretName: loki-bucket-creds
---
{{- end }}
