{{- if .Values.loki.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: loki-read
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/component: read
      app.kubernetes.io/instance: loki
      app.kubernetes.io/name: loki
  policyTypes:
    - Ingress
  ingress:
    - from:
        # From Grafana
        - podSelector:
            matchLabels:
              app: grafana
      ports:
        - port: http-metrics
          protocol: TCP
{{- end }}
