{{- if .Values.loki.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: loki-stack
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/instance: loki
      app.kubernetes.io/name: loki
  policyTypes:
    - Ingress
  ingress:
    # Allow stack compontents to communicate to eachother
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/instance: loki
              app.kubernetes.io/name: loki
    - from:
        # Metrics
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: prometheus
              operator.prometheus.io/name: prometheus
      ports:
        - port: http-metrics
          protocol: TCP
{{- end }}
