{{- if .Values.tempo.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: tempo-distributor
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/component: distributor
      app.kubernetes.io/instance: tempo
      app.kubernetes.io/name: tempo
  policyTypes:
    - Ingress
  ingress:
    - from:
        - namespaceSelector: {{- include "selector.namespace" . | nindent 12 }}
      ports:
        - port: 4318 # otlp-http
          protocol: TCP
        - port: 4317 # otlp-grpc
          protocol: TCP
        - port: 3200 # http
          protocol: TCP
        - port: 14268 # thrift-http
          protocol: TCP
        - port: 6831 # thrift-compact
          protocol: UDP
        - port: 6832 # thrift-binary
          protocol: UDP
        - port: 14250 # jaeger-grpc
          protocol: TCP
        - port: 9411 # http-zipkin
          protocol: TCP
{{- end }}
