apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grafana
spec:
  secretName: grafana-cert
  isCA: false
  dnsNames:
    - {{ include "grafana.hostname.long" . | quote }}
    - {{ include "grafana.hostname.short" . | quote }}
  issuerRef:
    name: local
    kind: ClusterIssuer