{{- if .Values.cloudflare.enabled }}
---
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-client-cert
  annotations:
    reflector.v1.k8s.emberstack.com/reflects: "cloudflare-certs/cloudflare-client"
# No data
---
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-grafana-cert
  annotations:
    reflector.v1.k8s.emberstack.com/reflects: {{ include "cloudflare.cert.grafana" . | quote }}
# No data
---
apiVersion: traefik.io/v1alpha1
kind: TLSOption
metadata:
  name: cloudflare-tls
spec:
  minVersion: VersionTLS12
  clientAuth:
    secretNames:
      - cloudflare-client-cert
    clientAuthType: RequireAndVerifyClientCert
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: cloudflare-middleware
spec:
  plugin:
    cloudflarewarp:
      disableDefault: false
---
{{- end }}