{{- if .Values.cloudflare.enabled }}
---
apiVersion: traefik.io/v1alpha1
kind: TLSOption
metadata:
  name: cloudflare-tls
spec:
  minVersion: VersionTLS12
  clientAuth:
    secretNames:
      - cloudflare-client-ca
    clientAuthType: RequireAndVerifyClientCert
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: cloudflare-middleware
spec:
  plugin:
    cloudflarewarp:
      disableDefault: false
---
{{- end }}