apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: prometheus
spec:
  secretName: prometheus-cert
  isCA: false
  dnsNames:
    - {{ include "prometheus.hostname.long" . | quote }}
    - {{ include "prometheus.hostname.short" . | quote }}
  issuerRef:
    name: local
    kind: ClusterIssuer