apiVersion: v1
kind: Secret
metadata:
  name: grafana-oidc-creds
  namespace: {{ include "unison.namespace" . | quote }}
  annotations:
    reflector.v1.k8s.emberstack.com/reflects: {{ printf "%s/%s" .Release.Namespace ( include "grafana.oidc.clientSecret.name" . ) | quote }}
