apiVersion: openunison.tremolo.io/v1
kind: Trust
metadata:
  name: grafana
  namespace: {{ include "unison.namespace" . | quote }}
spec:
  accessTokenSkewMillis: 120000
  accessTokenTimeToLive: 60000
  authChainName: login-service
  clientId: {{ include "grafana.oidc.clientId" . | quote }}
  clientSecret:
    keyName: {{ include "grafana.oidc.clientSecret.key" . | quote }}
    secretName: grafana-oidc-creds
  codeLastMileKeyName: lastmile-oidc
  codeTokenSkewMilis: 60000
  publicEndpoint: true
  redirectURI:
  - "https://{{ include "grafana.domain" . }}/login/generic_oauth"
  signedUserInfo: true
  verifyRedirect: true
